version: '3'
services:
  postgresql:
    image: postgres:11.4
    container_name: postgres-blog
    network_mode: host
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog
      - TZ=Etc/UTC