version: '3'
services:
  postgresql:
    image: postgres:11.4
    container_name: postgres-blog
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog
      - TZ=Etc/UTC